### ISSUE TITLE
Provide pre-built binaries

### ISSUE THREAD

**Issue by tijko** [tvrzna/emptty#100]
I've been writing the AUR pkgbuild and as is I have pushed the pre-built binaries to my own personal repository.

This is not ideal and AUR is pretty standard to have the upstream provide them.

We could setup a release for whenever there are new features (minor/major) bumps but that might be out of scope for this specific issue.

**Comment by tvrzna** [comment]
As I mentioned in [#75 ](https://github.com/tvrzna/emptty/issues/75#issuecomment-1284995580), I don't like the idea of storing binary in this repository since there is too many distros with different libc (even across glibc) versions and different architectures. You can admit, that Arch is only x86_64, however there are forks using also AUR.

I understand, that it's better for users to have binary from upstream, however quite common is also repacking of e.g. Debian or Ubuntu builds, which are provided for multiple architectures.

**Comment by tijko** [comment]
Having the binaries available with a download link upstream is merely standard practice.  There's no set of requirements that we must abide by.  I've been communicating with @orhun and he has been very helpful as he has maintained numerous AUR packages himself.

I've have no problem with setting up a Gitflow with hooks to check this repository.  Building out when necessary.  Unless you have other ideas, lmk.

**Comment by tvrzna** [comment]
I'm not exactly fan of having the binary at repo for specific distro due to the experiences with glibc changes. When the distro makes such a change I may be unawere of this and broken binary is still distributed. However bringing @orhun to this is a nuclear bomb and I feel like I don't have any other option.
I'm not exactly familiar with github action, please review the workflow.

**Comment by tijko** [comment]
> I'm not exactly familiar with github action, please review the workflow.

What you have is working well and were not needing all too much considering.

**Comment by tvrzna** [comment]
I've manually ran the package process on 0.11.0 and uploaded the artifact to the release. We'll see next release, if there is something I've missed.
