### ISSUE TITLE
Feature request: Last user as default

### ISSUE THREAD

**Issue by Vladimir-csp** [tvrzna/emptty#115]
Save last logged in user in `/var/cache/emptty/user` or `/var/cache/emptty/user-$tty`, preselect it next time.
Potential config options:
`SELECT_LAST_USER=false|per-tty|global`

There also needs to be a shortcut to re-select user.

**Comment by tvrzna** [comment]
Seems like nice idea. Emptty is CLI, shortcut would require some TUI or fiddling with echo off and text buffer. However I can imagine following prompt:
```
localhost login [LAST_USED_USER]: 
```
If no character is there, last user will be used, otherwise new user is selected. Also I think it would be better, if only successfully logged in users are saved. `DEFAULT_USER` will still have higher priority.
