### ISSUE TITLE
Shutdown and reboot keyboard shortcuts

### ISSUE THREAD

**Issue by fgallaire** [tvrzna/emptty#118]
Could it be possible to add shutdown and reboot keyboard shortcuts (for example ly uses F1 shutdown and F2 reboot) ?
I know it will not be so empt(t)y, but very useful !

**Comment by tvrzna** [comment]
I was thinking about it whole weekend. In past I was against it without thinking, but this time I looked into it. The problem is, that `emptty` is not TUI, but CLI, so there is no layer for reading inputs in Raw/Cbreak mode. And it looks like quite hard task for "just" catching shortcuts (without external library), that could brings also issues to the current behaviour.

But maybe I was looking on wrong type of solution.

**Comment by fgallaire** [comment]
Thanks for the time you took to think about it.
I really like how you work.

**Comment by noboruma** [comment]
What about adding a command mode like vim is doing:
`:shutdown` or `:reboot`
Username can only contain letters and digits, so if you type `:` from the username input, we could catch it and perform a different behavior?

**Comment by tvrzna** [comment]
That's an excellent idea!

**Comment by tvrzna** [comment]
It's implemented now, I think this feature with proposed handling deserves to be enabled by default. More in [readme](https://github.com/tvrzna/emptty/blob/2abb75bd4e30d247dda211db4bcd16c79805679a/README.md#commands).

**Comment by fgallaire** [comment]
Nice, but you're too fast, needs to think about it more !

**Comment by fgallaire** [comment]
What is really nice is the easy integration with the global CLI emptty design.

What needs more thinking:
1) Commands are nice, but not shortcuts, i.e. they are long. Could we have a short version (`:r`, `:p`, `:s`) ?
2) Should we have text printed with a reminder of the commands in the "UI" (when allow_commands is set to true) ?
3) As commands are a generic concept, should it be limited to shutdown/reboot or possibly configurable with any command we could need ?

**Comment by tvrzna** [comment]
Yes, the "hardest" part was to take it out of the authorization part.

1. I was thinking about shorter variants too, but I'm affraid it's too easy to make an error. And I think that confirmation `[y/N]` would be annoying.
2. It depends on what would be proposed. However since it's enabled by default, maybe the opposite situation needs to be reminded.
3. It could be little bit dangerous, those commands are run by root itself. But yes, that's the user's responsibility.
