### ISSUE TITLE
Make it possible to run xorg sessions as non-root users.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#12]
elogind and system-logind make rootless xorg sessions possible.

Refer to `man Xorg` for more details.

**Comment by tvrzna** [comment]
Hi, even I'd like to have it in emptty, I'm still unable to make it work. It will take some time, until I figure out.

**Comment by crocket** [comment]
A friendly reminder // Add `XORG_ARGS` option to custom sessions when you fix this issue.

**Comment by crocket** [comment]
I imagine that you can check whether xorg was compiled with elogind or systemd and execute xorg server as the login user.

**Comment by INetBowser** [comment]
@crocket  @tvrzna Has anyone of you been able to start the X server as non-root user?

**Comment by crocket** [comment]
With elogind, you can run xorg server as a non-root user. But, I run sway as a non-root user with seatd.
It's possible to have a system without elogind.

**Comment by tvrzna** [comment]
> Has anyone of you been able to start the X server as non-root user?

So far no progress, I've tried a few times make it work (not only in emptty), but always failed. It's simple to start Xorg as non-root user, but since I'm unable to prepare environment, I can't test it and finish it. For last few months it's frozen for me.

**Comment by tulsti** [comment]
Hello tvrzna,
I am using arch-linux and can start Xorg as a normal user. to do:

- login to a shell
- have an .xinitrc (mine has just a line "exec mate-session"
- my user is in the groups video and audio
- execute "startx". This will launch the X-server, and this by itself will execute the .xinitrc to start my mate desktop

**Comment by tvrzna** [comment]
Hello,
excuse me for late response.
Yes, this approach works and I've tried that too previously. The issue was that I was unable to mimic `startx` behaviour. And using directly `startx` would be meaningful only with `XINITRC_LAUNCH` option set to `true`. And that's not enough in my eyes.

**Comment by msharov** [comment]
I'll just barge in here, having found this project in my newsfeed. I've recently suffered through implementing this functionality for my own login project at https://github.com/msharov/loginx , and so have acquired some very tedious experience in the task. The X starting code is in usess.c . Perhaps you could figure out the problem by having another project to try besides startx. And, of course, if loginx doesn't work for you either, I'll appreciate getting a bug report about it.

**Comment by tvrzna** [comment]
Magical algorithm of Github saves the day! Loginx works out of box. Thank you very much, it just works with logind (Arch Linux and Debian). With elogind (Void Linux) I am still not successful, but someone more handy could figure out, what configuration of packages works.

**Comment by msharov** [comment]
What is the nature of the failure with elogind? Crash, hang, error message? What's in Xorg.0.log?

**Comment by tvrzna** [comment]
I'm currently on computer without the used virtual machine, but the issue (I believe it was more than that) was about denied permissions to the `/dev/tty7`. With Arch or Debian the tty is owned (by `logind`, I believe) by `<user>:tty` after login, however with `elogind` (with special packages build for x11 support) it remains owned by `root:tty`. When I change that manually before Xorg is started, the session starts, but it stucks (mouse is moving, no icon/menu work) without any information why it happened. I think it could be caused by incomplete changes in ownership for more "files", but still I have no intention to set ownership to any root file.

**Comment by msharov** [comment]
You are supposed to make the logged in user the owner of the tty. loginx does this in PamLogin in pam.c. At logout the tty owner is reset to root just below that in PamLogout.

Logind gives X file descriptors for the graphics device and the event sources, so if X starts and you can move the mouse, then all the logind-related functionality has succeeded. If the session doesn't start, it would be a problem with launching .xinitrc, such as missing environment variables. Switch to another tty and see what environment was set on the session process.

**Comment by tvrzna** [comment]
I thought logind handles ownership itself, but it could be caused by build parameters used in mentioned distros. I am going to implement that here too, thank you.

I did not realize, that the stuck moment could be caused by missing permission to `/dev/input`. But there's a working workaround by adding user into `input` group. But that will be just a part of man/README, how to troubleshoot this situation.

**Comment by msharov** [comment]
I don't know if logind changes tty ownership too, but loginx does it because it can work without logind.

The user should not be in the input group. For security reasons only X should have permissions to read the input devices raw. This is one of the reasons logind is needed for rootless X; logind gives X the input device file descriptors over DBus.

**Comment by tvrzna** [comment]
I've noticed, that the ownership was changes without modification from emptty. However it does not happen with elogind.

I am aware, that user should not be there. I also understand that it is bad advice to leave it in manual/readme, so I'll removed it until better troubleshooting advice is ready.

**Comment by crocket** [comment]
So, this issue is not going to be addressed?

**Comment by tvrzna** [comment]
It works in Debian and Arch, in Void (or theoretically any logind-free distro) it could work with correct configuration (I don't believe that addding user into `input` group should be considered as correct way). The basics are done, rootless Xorg is available with emptty.

**Comment by s3rj1k** [comment]
@tvrzna Can't get this to work under arch, what configurations are needed?

**Comment by tvrzna** [comment]
In `/etc/X11/Xwrapper.config` I have
```
needs_root_rights = no
allowed_users = anybody
```

And of course in `/etc/emptty/conf` is defined `ROOTLESS_XORG=true`.
