### ISSUE TITLE
Bash doesn't starts after login on any TTY

### ISSUE THREAD

**Issue by thealio** [tvrzna/emptty#125]
Hi
I start correcty the session , but I receive the following errors on the terminal

bash: xdg-user-dir: command not found
bash: xdg-user-dir: command not found
bash: xdg-user-dir: command not found
bash: xdg-user-dir: command not found
bash: xdg-user-dir: command not found
bash: stat: command not found
bash: tput: command not found
bash: fastfetch: command not found

also , the terninal is unusable, I cannot launch any command ( sudo , ls , all commands) as they are declared as "command not found"

It seems like the shell doesn't start, or something similar

This happens on any TTY I choose to log in from

**Comment by tvrzna** [comment]
Hello,
please tell me more about your distro/init, if you are using `.config/emptty` file and how you start emptty. It seems you don't have correctly defined/loaded your `PATH` environment variable.

**Comment by tvrzna** [comment]
The issue is more likely caused by the fact, that emptty ignores `.bashrc` in default configuration, so your config is not loaded at all. See [samples](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#script-with-sourced-etcprofile-using-loginshell), if it isn't the thing that could help you. Create `~/.config/emptty` file, use `chmod +x` on it and then place following into the file:
```bash
#!/bin/sh
Selection=true
LoginShell=/bin/bash --login

exec $@
```

This should still allow you to use selection, however it should use `.bashrc`.

**Comment by thealio** [comment]
Hi , and thank you so much!
This resolves the issue !

As feature request, it could be cool a commmand to launch from terminal (maybe a script on /bin/ ) that checks the user's current shell and shell config and auto-generate a .emptty file in user's $HOME basing on that

**Comment by tvrzna** [comment]
I'm glad it helped you!

Currently config generator is not planned, because it is quite complex task and would require wide network of people, that would provide own requirements. (e.g. I suggested `LoginShell=/bin/bash --login`, but your system required `LoginShell=/usr/bin/env bash --login`) . I think maybe better docs/man page/help would be better.

**Comment by thealio** [comment]
Thank you so much!

If this can be helpful, I made a little example post-script that may can help 

```
#!/usr/bin/env bash

# Define the file path
file="$HOME/.emptty"
#Check the file existence
echo "Create the file if it doesn't exist"
if [ ! -e "$file" ]; then
    touch $file
fi
# Start the file operations
echo "# A backup for $file is recommended"
cp $file $file.backup
echo "# Done"
sleep 1
# Write the config depending by the current shell
sleep 1
echo "Create the file if it doesn't exist"
sleep 1
# bash shell
if [ "$SHELL" = "/bin/bash" ]; then
echo "#!/usr/bin/env bash
Selection=true
LoginShell=/usr/bin/env bash --login

exec £@
" > $file
# fish shell
elif [ "$SHELL" = "/usr/bin/fish" ]; then
echo "#!/bin/fish
set Selection true
set LoginShell /bin/fish --login

exec dbus-launch £argv
" > $file
# Error message
else
echo "The shell is something else: $SHELL"
fi
##############
sed -i 's/\£@/$@/g' $file
sed -i 's/\£argv/$argv/g' $file
#####
sleep 1
echo "# Done"
sleep 1
echo "Check the content"
echo " "
cat $file
```

Regarding the issue, it's resolved, you can close this 

Again , many many thanks , this is an awesome piece of software !

**Comment by tvrzna** [comment]
Thank you for the example script, but as I mentioned, I'm currently not planning to implement one into emptty since required complexity is huge. However I hope everyone in need finds this!
