### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by 18gatenmaker** [tvrzna/emptty#21]
Hi :wave: I'm an Arch user with `emptty` on the AUR. I never used a WM before instead of a full DE, so I got 2 questions:

1. The title. If I try to start awesomewm (my current WM, still looking around). I need to:
- Boot
- Login on my tty
- Then type `sudo emptty`
- Then *again* type my pass
- Then login **again** on emptty
- Finally hit enter :tada: **done** :tada:

Is there a solution to this by possibly overriding the regular login screen?

2. Bonus, I said I am still searching for a WM to settle on, what do you guys recommend?

**Comment by tvrzna** [comment]
Hello,
I understand, why you use this approach, since many of Console Display Managers work this way, however `emptty` is standalone DM, that does not require logging in from classic (ag)TTY.

If you are already using some Display Manager, use `sudo systemctl stop display-manager` and `sudo systemctl disable display-manager` to disable current DM. Be sure, which DM you use to be able to revert this change.
Then you can `sudo systemctl enable emptty` and possibly `sudo systemctl start emptty`. If you have correct configuration in `/etc/emptty/conf`, you will see emptty started on TTY 7.

**Comment by 18gatenmaker** [comment]
Oh, i didn't know emptty had a service on its own! Thank you for the help!

**Comment by tvrzna** [comment]
To the second question, I suggest to try what suits you the best, nothing is better than own experience.
