### ISSUE TITLE
Question: allow offline building

### ISSUE THREAD

**Issue by surprized** [tvrzna/emptty#35]
I have no idea about how to code in Go, but I'd like to have a way to be able to build offline so I can package this in the Open Build Service.
Given two zip/tar.gz files with both repos, how could I handle this situation?

**Comment by tvrzna** [comment]
Hello,
`go mod vendor` in unzipped emptty folder with online environment provides guide how to setup emptty for offline build (tested). This feature downloads dependencies into `vendor` and sets information for following build.

Since I am not sure it is correct to provide this `vendor` folder already in this repository, I'll try to guide you how to do this manually and offline (with zip files of both repos).

* Unzip emptty zip/tar.gz file.
* Go to `emptty` unzipped folder.
* Create folder `vendor`
* Create `vendor/modules.txt` with following content (according `go.mod` file in emptty folder, I believe some fancy script could prepare the content):
```
# github.com/msteinert/pam v0.0.0-20200810204841-913b8f8cdf8b
## explicit
github.com/msteinert/pam
# github.com/tvrzna/emptty/src => ./src
```
* Create folder `vendor/github.com/msteinert/pam`
* Unzip pam zip/tar.gz file into `vendor/github.com/msteinert/pam` folder (mentioned folder should have inside file `transaction.go`)

When it's prepared this way, `make build` should work offline.

**Comment by surprized** [comment]
This works, thanks!
I am definitely going to prepare a script for it
