### ISSUE TITLE
Support S6 init system

### ISSUE THREAD

**Issue by altcoinpirate** [tvrzna/emptty#42]
I would like it if emptty would support the s6 init system in addition to the current ones( systemd, openrc, etc).
I have tested it in Artix Linux in the following way.  (I assume it would also work on other distros as well)

How:
A directory must be created at "/etc/s6/sv/emptty"
It will contain three files.
A file named "dependencies" with the contents "udevadm"
A file named "type" with the contents "longrun"
A file named "run" with the contents "#!/usr/bin/execlineb -P" on the first line and "exec /usr/bin/emptty -d" on the second.

**Comment by tvrzna** [comment]
Hello,
I've been thinking about s6 support for long time, but never had enough time to learn it.
Thank you for the template, I'm going to use it as soon as possible.

**Comment by tvrzna** [comment]
I'm not sure, if I understand the principle of S6 compile correctly, but according `/usr/share/libalpm/scripts/s6-rc-db-update-hook` there is no simple way how to compile service database and still cover all S6 distros.

**Comment by altcoinpirate** [comment]
I'm not exactly sure what you mean (I know very little about package manager hooks and very little about compiling s6 databases), but after looking at the hook and script files it seems that installing any package that changes a file in the /etc/s6/sv/* directory will trigger an automatic database update via the s6-rc-db-update hook, and, only if installing or upgrading, trigger the help information via the s6-rc-install hook.
My understanding is that emptty would not need to compile anything, and if another distro supported s6, either that distro or the s6-base package would be responsible for properly compiling the databases.  Please correct me if I am wrong.
I would assume the pacman hook would work on all linux distros that use pacman, including Obarun and Artix, the two main s6-compatible distros, as well as Mere which is in alpha stage.
I really don't know how other s6 distros would handle this, but the only other s6 distro I could find is the independent distro Mutiny, which does not yet have a bootable system.
I hope this helps.  :)

**Comment by tvrzna** [comment]
I've made clean installation of Artix with s6, pacman provides mentioned hook and updates/compiles new database of services. However without this hook it throws an error, that emptty is not in compiled database (if service is created before the hook), if I try just `s6-rc-bundle-update add default emptty`.
I'd like to find a solution, that does not require existence of the pacman hook since there are attempts to port s6 into also into Void and many other distros. And also Artix does not use default path to compiled database.
Until the solution is found, I'm affraid users with S6 have to recompile themselves.

Thank you for additional clarification :)
