### ISSUE TITLE
emptty meddles with PATH variable.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#45]
PATH is supposed to be

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/12/bin:/usr/lib/llvm/11/bin
```

But, with emptty, it becomes

```
/bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/12/bin:/usr/lib/llvm/11/bin
```

I think it's best for emptty to not touch PATH.

**Comment by tvrzna** [comment]
Can you please, provide your start script? It only uses the PATH from root, there is no other operation with it. However there was a bug with duplicated start of ~/.config/emptty file, if selection is true (48cab88). This could perform its duplication.

**Comment by crocket** [comment]
~/.config/emptty-custom-sessions/sway-with-user-env.desktop
```
Name=Sway with user environment
Exec=/home/guardian/.config/emptty-custom-sessions/sway-with-user-env
Environment=wayland
```
~/.config/emptty-custom-sessions/sway-with-user-env
```
#!/bin/sh

. ~/.env

exec sway
```
~/.env
```
...

export PATH="$HOME/.local/bin:$PATH"

...
```

**Comment by tvrzna** [comment]
I've tried to reproduce and there is no way that emptty do something with `PATH`. The only place, where `emptty` does something with `PATH` is in `src/login.go` on line 91:
```
usr.setenv(envPath, os.Getenv(envPath))
```

This line took `PATH` from root (or any superuser which starts `emptty`) and inserts it into newly created map of evironmental variables from logged in user. If anything causes some changes in `PATH`, it must be something inside `~/.env` (as you've mentioned `export PATH="$HOME/.local/bin:$PATH"` in case it would start `sway-with-user-env` twice), sway itself or something like `.bash_profile`.

The only issue could be caused by overriding of `PATH` defined by `~/.pam_environment` with the root's `PATH`. But it would not cause any duplication.

**Comment by crocket** [comment]
Does emptty source `~/.profile` during login?

**Comment by tvrzna** [comment]
No, emptty doesn't source `~/.profile`. Isn't possible, that your shell or terminal emulator does? Or that it is recursively started somehow? I've tried some other options and I could not reproduce this issue with latest (unreleased) version.

**Comment by crocket** [comment]
Somehow, this issue still plagues me only when I log in emptty.

**Comment by tvrzna** [comment]
I've tried to reproduce this one more time and I can't still achieve the same result as you have described. Please, try to remove `. ~/.env` from your `/home/user/.config/emptty-custom-sessions/sway-with-user-env` and then check, if `PATH` looks better. I assume the only reason emptty gives you this result is the fact, that it supports custom desktop definitions and it could cause, that anything, what works with `PATH`, could run multiple times.
I think you expect it it caused by taking the PATH from root, but the only reason it is specificaly mentioned there is the fact, that taking all root environment could cause running of malicious scripts.

**Comment by crocket** [comment]
`os.Getenv(envPath)` returns a sane value of $PATH. What is `usr.setenv`?

I think something is reversing the order of some elements of $PATH.

**Comment by tvrzna** [comment]
Due to [root LD_PRELOAD injection](https://xn--1xa.duncano.de/emptty-security-issue.html#root%20LD_PRELOAD%20injection) it does not take all environmentals, but only necessary variables. `usr.setenv` is setting/copying of defined variables into new user environment, nothing else. Emptty does nothing else with `PATH` than copy it from root's environment into the user's one.

**Comment by crocket** [comment]
Eliminating `. ~/.env` doesn't fix the issue.

**Comment by tvrzna** [comment]
Also try to echo `PATH` in `/home/user/.config/emptty-custom-sessions/sway-with-user-env` to some file, if there is nothing wrong even before. (I'd recommend to use `>>` to see, if it isn't started twice).

**Comment by crocket** [comment]
With

```
#!/bin/sh

. ~/.env

echo $PATH >> ~/path.log

exec sway
```

path.log is

```
/home/guardian/.local/bin:/bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/12/bin
```

**Comment by tvrzna** [comment]
It looks like the wrong `PATH` is comming from root. The issue with emptty is not running standard `.profile` procedure, which would replace that long content. Please, also try to log as root on TTY to see `PATH` variable.

As you can see in [source code](https://github.com/tvrzna/emptty/blob/master/src/login.go#L93), there is nothing more than copy from root environment.

**Comment by crocket** [comment]
If I log in as root on tty, PATH is

```
/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/12/bin
```

**Comment by crocket** [comment]
Can you provide me with a patch that records `os.Getenv(envPath)` in `/tmp/path` or some other place?

**Comment by tvrzna** [comment]
Try [45-print-path.patch](https://emptty.tvrzna.cz/45-print-path.patch), it's created only as `git diff > 45-print-path.patch`, so I hope it will work.
It creates 3 files:

1. `/tmp/path-start`; contains only `os.Getenv(envPath)`.
2. `/tmp/path-after-start`; contains `usr.getenv(envPath)` after PAM environmentals are inserted, but before `os.Getenv(envPath)` does.
3. `/tmp/path-end`; last value of `usr.getenv(envPath)`, when method `defineEnvironment` finishes.

**Comment by crocket** [comment]
path-start
```
/bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/12/bin
```
path-after-start
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/12/bin
```
path-end
```
/bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/12/bin
```

**Comment by tvrzna** [comment]
It looks like it should not overwrite `PATH`, if it's loaded from PAM. I think the solution is new configuration option to avoid overwriting `PATH`, if is not blank after PAM. (Since no one else complained, I'm afraid to put this as default behaviour, because it would be a breaker.)

**Comment by crocket** [comment]
Why don't you break it and fix it? After doing it once or twice, it will probably be fixed for everyone.

**Comment by crocket** [comment]
Why was PATH broken before defineSpecificEnvVariables(usr)?

**Comment by tvrzna** [comment]
I'll think about it. It's hard to decide, since I won't be affected (no `PATH` from PAM in my case). Almost nobody reads changelog, so it could cause some confusion.
Your `PATH` before `defineSpecificEnvVariables` is broken, because your root has broken `PATH` definition. This is nothing related to emptty, it's just your configuration.

**Comment by crocket** [comment]
On my sytem, `/etc/profile` reads `/etc/profile.env` which contains

```
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/12/bin'
```

**Comment by tvrzna** [comment]
The broken `PATH` is probably from state, when no PAM is involved. It could be defined by init system, which tooks your value and puts its own default as prefix or something like that.

**Comment by crocket** [comment]
I made openrc init system record the value of $PATH during boot. I got this.

```
/lib/rc/sbin:/lib/rc/bin:/bin:/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/lib/llvm/12/bin
```

Obviously, openrc init scripts are messing with PATH.

And, /etc/pam.d/system-login has this line.

```
session		required	pam_env.so envfile=/etc/profile.env
```

which sets PATH to the right value.

**Comment by tvrzna** [comment]
I hope it will be better now with provided fix, which does not set `PATH` from root, if it is already set from PAM. It's always a magic to track these kind of problems since every distro and every installation could be so different.

**Comment by crocket** [comment]
The problem was that OpenRC modifies PATH in order to cater to openrc init scripts written in bash.
PAM restores the correct value of PATH.

Thanks for the fix.

**Comment by crocket** [comment]
It's finally fixed.
