### ISSUE TITLE
How to change the EMPTTY text at login screen

### ISSUE THREAD

**Issue by enricofadly** [tvrzna/emptty#48]
how do i can the emptty text at login screen? I have no idea because I don't have much knowledge about linux

**Comment by tvrzna** [comment]
Hello,
please take a look at the [screenshot](https://github.com/tvrzna/emptty/blob/master/screenshot.png).

If you want to change the first line, you can modify your `/etc/issue`, this would have effect on all your TTYs. If you want to just hide this part, you can set `PRINT_ISSUE` in your `/etc/emptty/conf` to `false`.

If you want to change only that emptty part, you have two options. The first is to create `/etc/emptty/motd` and insert any text. This allows ANSI colors, however it does not support running any script, it's just plain text. If you are interested in dynamic content, you can create `/etc/emptty/motd-gen.sh` file, adds to it executable flag (`chmod +x /etc/emptty/motd-gen.sh`) and then update `DYNAMIC_MOTD` to `true` in your `/etc/emptty/conf`. This would allow you to use e.g.
```
#!/bin/sh
echo 'Hi there'
```

I would recommend to try just plain text, because dynamic motd could easily do unwanted stuff.

**Comment by enricofadly** [comment]
Okay sir problem is solved, thanks for you help and keep up the good work (y)
