### ISSUE TITLE
Auto login after logout

### ISSUE THREAD

**Issue by vuongkienthanh** [tvrzna/emptty#49]
I'm on linux mint xfce 20.2. My setting:
```
DEFAULT_USER=*secret
AUTOLOGIN=true
AUTOLOGIN_SESSION=startxfce4
```
Others are default.
Autologin works fine, but even after logout !?

**Comment by tvrzna** [comment]
Hello,
please excuse my late response.

It is expected behaviour, `emptty` performs only single login and it ends on logout. The init system restarts emptty with previous configuration and that means another autologin. I believe you should look for lock screen/screensaver with password protection to achieve expected behaviour.

**Comment by vuongkienthanh** [comment]
May I request the feature that you can select another windows manager after logout?

**Comment by tvrzna** [comment]
Wouldn't be easier to not define `AUTOLOGIN_SESSION` to get a selection each time?
I'm not sure if I can distinguish the logout action (D-Bus is not part of emptty) from the shutdown action and I can imagine some malicious intentions from this flaw.
