### ISSUE TITLE
XDG_CONFIG_HOME will break neovim after su

### ISSUE THREAD

**Issue by rhjdvsgsgks** [tvrzna/emptty#50]
`XDG_CONFIG_HOME` will be set to  `/home/user/.config` by emptty. after login to de, open a console and type `su`, `XDG_CONFIG_HOME` will also be passed to root environment, therefore neovim will load config from `/home/user/.config/nvim/init.vim` instead of `/root/.config/nvim/init.vim`. is this a expected behavior?

**Comment by tvrzna** [comment]
If envorinment is passed to root from user, the issue is calling with the `su` command. However it could be caused by emptty by not sourcing `~/.profile`, `/etc/profile.d/` and others, which could set alias to `su` command with expected behaviour. Please, try to read manual page of `su`, to run the command `su -` or to check which `.profile` files should be sources at login.

**Comment by rhjdvsgsgks** [comment]
i checked there is no stuff relevant to `XDG_CONFIG_HOME` or `su` in my `/etc/profile.d/` and `~/.profile`,  alias also not changed by sddm (which is my previous dm, and it don't have this issue). after simply searching in sddm's source code, i found that sddm will not set `XDG_CONFIG_HOME` by default, but emptty will, that's why i opened a issue here.

**Comment by tvrzna** [comment]
It is fallback for special cases, try to log into different TTY without any WM/DE and Display Manager. In my system it behaves the same way as you've described in first post. `su` does not do anything with `XDG_CONFIG_HOME` directly, it inherits all environmental variables, unless you use `su -` instead of `su`.
However if it will behave differently in your case on TTY, I'll add a new config option to skip setting of any XDG variable and let their creation on PAM/D-Bus/etc.

**Comment by rhjdvsgsgks** [comment]
"`su` does not do anything with `XDG_CONFIG_HOME` directly" is expected behavior i know, and that's also my expected. i just don't want dm(emptty) set `XDG_CONFIG_HOME` manually (at least add a option for it)
