### ISSUE TITLE
Corrupted pseudographic logo at silent boot

### ISSUE THREAD

**Issue by serugeix** [tvrzna/emptty#57]
1. Disable all messages at boot(aka silent boot, see https://wiki.archlinux.org/title/silent_boot)
2. reboot

Look at the screenshot: https://imgur.com/a/hrb62pA

**Comment by tvrzna** [comment]
Hello,
I've installed clean Arch Linux into VirtualBox, followed steps from Arch Wiki to make silent boot and I could not replicate the issue (It could be caused by the fact, that it is installed in VirtualBox). However I've already met this kind of corrupted logo previously and the solution used to be just to rebuild the emptty.

If it still remains, please try to change your font your console set your custom `/etc/emptty/motd`.

Please, let me know, if this worked.
