### ISSUE TITLE
Feature request: max retry count before "hard failing"

### ISSUE THREAD

**Issue by RossComputerGuy** [tvrzna/emptty#58]
I've noticed an issue with the autologin system where if the session fails, it keeps on trying to load it. Maybe it would be good idea to add a `MAX_RETRY` option and a `RETRY_DELAY` so people can choose how many tries can occur before emptty decides to try stop. The delay option would give people enough time so they could see any error messages.

**Comment by tvrzna** [comment]
Usually emptty waits until user presses Enter to allow restart, however I see there are still unhandled errors from starting the session. So this requires the fix, that's just wrong; `RETRY_DELAY` is not necessary.
But the `MAX_RETRY` seems to be more interesting, because it can catch the issues even the session does not return any error.

**Comment by RossComputerGuy** [comment]
I'm running v0.6.2 and it doesn't wait for enter to be pressed before continuing, it just loops.

**Comment by tvrzna** [comment]
Yes, as I told - usually it waits, but in this case there is unhandled error from starting/running the session and it just does not wait. The `MAX_RETRY` option needs to be there also to prevent situation, when the session starts and then stops immediately without any error.

**Comment by RossComputerGuy** [comment]
Alright. Also, I think the `MAX_RETRY` option should allow for `-1` which allows for infinite retries, `0` would only try once, `1` would try 2, and so on.
