### ISSUE TITLE
Add a configure item to automatically select a session when autologin?

### ISSUE THREAD

**Issue by fkxxyz** [tvrzna/emptty#6]
I  configure the autologin. But I have installed many desktop environments, it is inconvenient to manually select one.

**Comment by tvrzna** [comment]
Hello,
try https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#emptty-as-config .
However this approach doesn't support starting with `.xinitrc`, there could be an option to read info from user config file and start preselected command with `.xinitrc`.

**Comment by tvrzna** [comment]
Hello, configuration `AUTOLOGIN_SESSION` has been added.
This param must equals an end of "exec" param in session definition (e.g. `openbox-session` instead of just `openbox`). Then selected session behaves just like manually selected one - could be started with or without .xinitrc and is saved as last used desktop (in case of disabled autologin/auto-select).
