### ISSUE TITLE
Error in service module

### ISSUE THREAD

**Issue by raiguard** [tvrzna/emptty#61]
I get this error when leaving my PC on for a while before logging in, or pretty consistently when I log back out after being logged in. I will type my username, hit enter, then emptty will flash and "reset". However, the password field is still the one that is active. Once I type my password and hit enter, it brings me not to the WM selection, but to the bash shell. Every so often, emptty will come back up, but my input is still sent to the bash shell:

![image](https://user-images.githubusercontent.com/3515394/160737056-cb74d856-e4d6-4982-a7cc-e1d7f16a6d73.png)

I reproduced the error by logging out, and the log only had one line:

```
2022/03/29 20:05:22 Error in service module
```

Not sure what to make of this.

My configuration is left at default, except for `TTY_NUMBER=1`.

**Comment by tvrzna** [comment]
It looks like you have still allowed getty service at TTY1 and it duplicates your input; so when you log in first time, you start WM and also log in to your getty. This is caused by the fact, that emptty is not that much prepared for systemd and the TTY selection is not defined by service name.
So please, try `systemctl status getty@tty1` and if it's active, you need to disable and stop that service.

**Comment by raiguard** [comment]
Thank you, that resolved the issue!
