### ISSUE TITLE
Allow rootless Xorg when not in daemon mod but under root user.

### ISSUE THREAD

**Issue by s3rj1k** [tvrzna/emptty#69]
Basically all that needs to be changed to support running rootless Xorg when not in daemon mode but still with root user permission is to change all 

```
if x.conf.RootlessXorg && x.conf.DaemonMode {
```

to

```
if x.conf.RootlessXorg && (x.conf.DaemonMode || os.Getuid() == 0) {
```

in

```
src/session_xorg.go:43: if x.conf.RootlessXorg && x.conf.DaemonMode {
src/session_xorg.go:52: if x.conf.RootlessXorg && x.conf.DaemonMode {
src/session_xorg.go:94: if x.conf.RootlessXorg && x.conf.DaemonMode {
```

This is needed when `emptty` is used as `/bin/login` replacement and invoked from `agetty`.

systemd `/etc/systemd/system/getty@tty1.service.d/custom.conf` config looks like this in this case:

```
[Service]
ExecStart=
ExecStart=-/sbin/agetty --login-program=/usr/bin/emptty --noclear --noissue --nohints --nohostname --skip-login - $TERM
```

**Comment by s3rj1k** [comment]
https://github.com/tvrzna/emptty/pull/70

**Comment by s3rj1k** [comment]
@tvrzna PTAL when able, thanks.

**Comment by tvrzna** [comment]
@s3rj1k I'm sorry for this late response. I don't think proposed solution is correct. Xorg requires parameter `-keeptty` and this is simply enforced by daemon mode (since it runs on configured TTY). If we want to have this feature, it requires to compare `x.conf.ttyPath()` with current TTY (`ps -p [process-id] -o tty --noheaders`, visible in `daemon.go:evaluateIssueVars()`, but I'm not sure how it works with busybox).
The question is does your non-daemon emptty show correct TTY in issue. If so it could be done that way and it would be safe.

**Comment by s3rj1k** [comment]
> I'm sorry for this late response.
No problem, really.

I've just checked with my setup, what if I specify different TTY in config, like `agetty` starts `emptty` on TTY1 but in `emptty` config TTY is 7.

So I does not work in any combination, I assume that it is a DBUS issue or something with `/dev/tty` permissions, so the only working way is to keep TTYs same in `agetty` and in `emptty` config.

```
root         441  0.9  0.2 2588536 18492 tty1    Ssl+ 10:57   0:04 /usr/bin/emptty
```

This is how I can see `emptty` process when it is run in non-daemon mode under `agetty`.

```
# readlink /proc/441/fd/0
/dev/tty1
# readlink /proc/441/fd/1
/dev/tty1
```

So I assume `emptty` should detect TTY correctly in this case.

**Comment by tvrzna** [comment]
> So I does not work in any combination, I assume that it is a DBUS issue or something with `/dev/tty` permissions, so the only working way is to keep TTYs same in `agetty` and in `emptty` config.

That's the point of mentioned check. If it does not run as `root`, it will fail on `/dev/tty[X]` permissions (it needs to change its owner to run rootless).

> So I assume emptty should detect TTY correctly in this case.

I don't think it should be detected to run on same TTY since config defines the target. So we can remove the check for daemon mode and let the user fail or we can add the check for config and current TTY. Sadly `readlink /proc/PID/fd/0` can not be trusted.

**Comment by s3rj1k** [comment]
> we can remove the check for daemon mode and let the user fail

would work for me, if we do go this way, change should be noted in docs

(all of that rootless Xorg is really pain in ones a*s)

**Comment by tvrzna** [comment]
Please, take a look on these changes. I hope it helps a little bit. If you want to use a different TTY, you don't have to change configuration but only the start script to `emptty -t [TTY_NUMBER]`.

**Comment by s3rj1k** [comment]
@tvrzna Yep, latest commits work for me with this getty config.
```
$ cat /etc/systemd/system/getty@tty1.service.d/custom.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --login-program=/usr/bin/emptty --login-options='--tty 1' --noclear --noissue --nohints --nohostname --skip-login - $TERM
```

Thanks!
