### ISSUE TITLE
Authentication failure even tho all is well

### ISSUE THREAD

**Issue by qube-03** [tvrzna/emptty#76]
hi! im using emptty to autologin to my system since my usecase doesnt require me to put in my password each time.
however i have some issues currently. my /etc/emptty/conf file has autologin turned on, the DEFAULT_USER defined and the user is in the nopasswdlogin group. However emptty still gives me the authentication failure error. i also have turned on the default xauth option.
any help is appreciated.

more info:
os: Devuan 4 Chimaera
init: runit
shell: zsh
kernel: 5.10.0-19
emptty version: 0.9.0-2-g9ffa8dd

**Comment by qube-03** [comment]
after adding the line `auth sufficient pam_succeed_if.so user ingroup nopasswdlogin` to the file /etc/pam.d/emptty i now the the error "Permission denied", very interesting.

**Comment by tvrzna** [comment]
Hello,
have you used PAM file for Debian? Because if you've used the standard one, it could be incompatible with Devuan.

**Comment by qube-03** [comment]
i should add, running emptty just from command line tells me "Authenticate OK" but then directly afterwards "Permission denied". the 'emptty' file in /etc/pam.d/ is even owned by my user and has executable rights

**Comment by tvrzna** [comment]
[Standard PAM](https://github.com/tvrzna/emptty/blob/master/res/pam) file works fine with Void and Arch Linux, [Debian PAM](https://github.com/tvrzna/emptty/blob/master/res/pam-debian) is probably better choice for Devuan rather than the standard one. I believe the only issue is in this configuration. Please, compare you `/etc/pam.d/emptty` with mentioned Debian PAM. If the issue persists (even after reboot), please post your `/etc/pam.d/emptty` file.
