### ISSUE TITLE
Sway keybinds doesnt work

### ISSUE THREAD

**Issue by timsofteng** [tvrzna/emptty#85]
Hello. I'm trying to run sway session with emptty but keybinds don't work.
Everything is find if I run same command from tty after login.

Here is what I'm trying to do
```
> cat .config/emptty-custom-sessions/sway.desktop
Name=Custom Sway
Exec=dbus-run-session sway
Environment=wayland
```

log is here
https://0x0.st/Hsxk.txt

I guess emptty doesn't read my .zshrc and .zprofile

Receipt from man didn't help. Shell script doesn't understand zsh syntax. 

```
> cat .config/emptty
#!/bin/sh
Selection=true

# source /etc/profile does not have any effect
. ~/.zprofile 
. ~/.zshrc 

exec dbus-run-session $@
```

**Comment by tvrzna** [comment]
Hello,
I'm sorry that I'm replying so late. I can't reproduce it, but as you mentioned, it could be caused by not running profile scripts. Try to remove second `dbus-run-session` (if it's not just relic from previous attempt) and into your `.config/emptty` file add `LoginShell=/bin/zsh -l` ([description](https://github.com/tvrzna/emptty/blob/master/SAMPLES.md#script-with-sourced-etcprofile-using-loginshell)). That should perform login command with zsh and load all its profile scripts.

**Comment by timsofteng** [comment]
@tvrzna unfortunately it doesn't accept this command
`/home/tim/.config/emptty:3: command not found: -l`

**Comment by tvrzna** [comment]
Looks like your `/bin/sh` is an alias for `zsh`, however it should not cause issue (although it requires to be fixed to support quotes/apostrophes; see commit 6b0a2cd).
I'm still not able to reproduce the issue, it works out of box to me. Can you, please, provide more informations? (changes in `/etc/emptty/conf`, your OS, your Sway config, etc.)
