### ISSUE TITLE
Allow custom user sessions.

### ISSUE THREAD

**Issue by crocket** [tvrzna/emptty#9]
I think custom user sessions could be stored in `~/.config/emptty/custom-sessions`.

**Comment by tvrzna** [comment]
Looks like a good idea, but I afraid the folder must be `~/.config/emptty-custom-sessions`, even it could be an antipattern. The reason is to prevent destroying custom `~/.config/emptty` scripts/settings.

Also I think it should provide custom sessions from `/etc/emptty/custom-sessions` and `~/.config/emptty-custom-sessions` together since use-cases exist for both variants.

**Comment by crocket** [comment]
I think that's not a bad idea as long as they are documented.
