### ISSUE TITLE
Can I have a bash shell as one of my desktop sessions?

### ISSUE THREAD

**Issue by alexflint** [tvrzna/emptty#95]
With just this in my ~/.config/emptty:
```
Exec=bash
```
when I log in using emptty I am immediately logged out again. The log shows "Starting bash" and then on the next line, "bash finished". Why? What is the reommended way to have of my session options be a bash file?

**Comment by tvrzna** [comment]
Emptty is not meant to provide this kind of functionality. To be honest, agetty is much better choice in this case. However this could be achievable by little patch -> in `session.go` needs to be set
```go
session.Stdout = os.Stdout
session.Stderr = os.Stderr
session.Stdin = os.Stdin
```

Then you have to make sure you've called `bash --login` instead of just `bash`, and that you have `Env=wayland` (to prevent starting of Xorg). And also make sure you have set your `$TERM` env variable.
